### ISSUE TITLE
Optimize download as well ?

### ISSUE THREAD

**Issue by notzippy** [wolfden/Coding#1]
Trying it, works well. Do you think optimizing the download location would be a good addition to this script as well ? Feel free to close if not applicable...

**Comment by wolfden** [comment]
Hi! which file are you referring to?

I think you are referring to the bash script of rsync, have a look at the iso_rsync file as I have just rewritten the rsync bash file to python.   If you run across errors or anything let me know :)

https://github.com/wolfden/Coding/blob/master/python%20files/iso_rsync

**Comment by wolfden** [comment]
don't forget to edit location of local folder of  the iso folder in iso_rsync

**Comment by notzippy** [comment]
Sorry ! Thought there was only one file in the project should have checked ... :-/
[run_update](https://github.com/wolfden/Coding/blob/master/python%20files/run_update)
was what I was referring to

**Comment by wolfden** [comment]
No problem, ummmm, can you explain more of optimize download location?  Like sort the mirrors to find fastest mirror?  The downloading of packages is handled by entropy the package manager, so really nothing more I can do with that.

**Comment by notzippy** [comment]
Yes, that is it, sorry for not being more specific to begin with, typically I use rigo to update the system, but this seems to be a more inclusive. 

Also you may want to add a check for the [return code](https://docs.python.org/2/library/subprocess.html#subprocess.Popen.returncode) on your process calls and halt if something fails..

**Comment by wolfden** [comment]
Thanks for the feedback on add a check, I will look into that later.  

The intentions of this script was to take an installed system and upgrade it without human interaction other than the user typing out the command.

I do like the idea of mirror sort, but the only way I can see a way to implement it is via a prompt "would you like like to sort your mirrors?"  input of yes or no would continue the process, but than a person is stuck with that prompt every time.  If I build it directly into the code, it will run each and every time, nothing wrong with that, but seems unnecessary as a user only needs to run mirror-sort once per install unless they move around the world a lot.

If a menu system was implemented like below, it could work, but again a user is having to interact with it by selecting.  Not a big deal I guess unless one set up a cron job.

Select which repo to optimize (1-3)
1.mirror-sort - weekly
2.mirror-sort - main
3.mirror-sort - limbo
To start upgrade immediately select 4
4.begin upgrade

Unless you know of a different way.  I have just woke up to start my day so I don't have all the cobwebs  out of my head yet, augh mornings....  Thanks for the input so far!

**Comment by notzippy** [comment]
You could do an [input with a timeout in python](http://stackoverflow.com/questions/1335507/keyboard-input-with-timeout-in-python) so that if they want to do a mirror sort they can choose an option, or you could pass in an arguement to do a mirror sort. Perhaps a command line argument would be the better solution, then you could schedule once a month to update the mirrors in your cron script...

**Comment by wolfden** [comment]
Great ideas, gives me some stuff to research and learn more about python  :)  

Thanks!

**Comment by wolfden** [comment]
run_update [--limbo] [--main] [--weekly] implemented, haven't looked at return code yet...

**Comment by wolfden** [comment]
Script should now be checking and failing if commands fail, at least it did in my testing,  thanks again for  the feedback :+1:
